services:
  funpayow:
    build:
        context: .
        dockerfile: Dockerfile_main
    restart: always
    volumes:
      - ./.local:/usr/src/funpayow/.local
      - ./alembic/versions:/usr/src/funpayow/alembic/versions
    env_file:
      - ./.env

  funpayow_scrap:
    build:
      context: .
      dockerfile: Dockerfile_scrap
    restart: always
    volumes:
      - ./.local:/usr/src/funpayow/.local
      - ./alembic/versions:/usr/src/funpayow/alembic/versions
    env_file:
      - ./.env

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "funpayow"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
